name: Build

on:
  push:
    paths:
      - '*.c'
      - '*.h'
      - 'Android.mk'
      - '.github/workflows/build.yml'
  workflow_dispatch:
    inputs:
      abi:
        type: string
        description: ABI
        default: armeabi-v7a
        required: true
      platform:
        type: string
        description: PLATFORM
        default: "19"
        required: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compile
        run: |
          if [ ${{ github.event_name }} != "push" ]; then
            $ANDROID_HOME/ndk/24.0.8215888/ndk-build NDK_PROJECT_PATH=. APP_BUILD_SCRIPT=./Android.mk APP_ABI=${{ inputs.abi }} APP_PLATFORM=android-${{ inputs.platform }}
          else
            $ANDROID_HOME/ndk/24.0.8215888/ndk-build NDK_PROJECT_PATH=. APP_BUILD_SCRIPT=./Android.mk APP_ABI=armeabi-v7a APP_PLATFORM=android-19
          fi

      - name: Uplaod
        uses: actions/upload-artifact@v4
        with:
          name: CVE-2016-5195(dirtycow)
          path: libs/${{ inputs.abi }}/*
